version: 1.0.{build}
branches:
  only:
    - ci
image: Visual Studio 2015
#install:
#  - echo true
configuration: Release
environment:
  CMAKE_PREFIX_PATH: C:\Qt\5.12.2\msvc2017_64
build_script:
  - ./build.bat